# Generated by Django 3.1.7 on 2021-03-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.BooleanField()),
                ('relocate', models.BooleanField()),
                ('study', models.BooleanField()),
                ('work', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_8_00', models.BooleanField()),
                ('time_10_00', models.BooleanField()),
                ('time_12_00', models.BooleanField()),
                ('time_14_00', models.BooleanField()),
                ('time_16_00', models.BooleanField()),
                ('time_18_00', models.BooleanField()),
                ('time_20_00', models.BooleanField()),
                ('time_22_00', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('about', models.TextField()),
                ('rating', models.FloatField()),
                ('picture', models.TextField()),
                ('price', models.IntegerField()),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.goals')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.monday')),
            ],
        ),
    ]
